name: GitHub-Profile-3D-Contrib
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      # PASSO CORRIGIDO AQUI (nova sintaxe):
      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.0
        with:
          github_user: "vallzin"  # Nome alterado de USERNAME para github_user
          image_output: "./profile-3d-contrib"  # Agora é um input direto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "Update 3D contribution graph" || echo "No changes"
          git push
